import type { AnalysisResult, Severity } from '../types';
import { escapeMarkdownCell as cell, formatMs, hookShare } from '../utils';
import { BaseReporter, ReporterOptions } from './BaseReporter';
import { serializeResult, topHooks } from './serialize';

const ICON: Record<Severity, string> = { error: '🔴', warning: '🟡', info: '🔵' };

/** GitHub-flavoured Markdown, suitable for PR comments and job summaries. */
export class MarkdownReporter extends BaseReporter {
  readonly type = 'markdown' as const;
  readonly extension = 'md';

  render(result: AnalysisResult, options: ReporterOptions = {}): string {
    const data = serializeResult(result);
    const s = data.summary;
    const out: string[] = [];

    out.push('# 🪝 Hookyy report', '');
    out.push(`**Framework:** ${data.framework} · **Hooks:** ${s.totalHooks} · **Scenarios:** ${s.totalScenarios} · **Hook executions:** ${s.totalExecutions}`, '');
    out.push(
      s.issuesFound === 0 && s.totalHooks === 0 && data.warnings.length
        ? '⚠️ **No hooks could be audited from this report** (see below).'
        : s.issuesFound === 0 && s.totalHooks === 0
        ? 'ℹ️ **No hooks found in this report**, so there was nothing to audit.'
        : s.issuesFound === 0
        ? '✅ **No hook issues found.**'
        : `**${s.issuesFound} issue(s):** ${ICON.error} ${s.errorCount} error · ${ICON.warning} ${s.warningCount} warning · ${ICON.info} ${s.infoCount} info`,
      '',
    );

    for (const w of data.warnings) out.push(`> ⚠️ ${w}`, '');

    const top = topHooks(result);
    if (top.length) {
      const share = hookShare(s);
      out.push('## Where the time goes', '');
      out.push(
        share !== undefined
          ? `Hooks took **${formatMs(s.totalHookTime)}** of ${formatMs(s.totalTestTime)} test time (**${Math.round(share * 100)}%**).`
          : `Hooks took **${formatMs(s.totalHookTime)}**.`,
        '',
        '| Costliest hooks | Runs | Total | What it does |',
        '| --- | ---: | ---: | --- |',
      );
      for (const h of top) {
        const runs = h.executions.filter((e) => !e.skipped).length;
        out.push(`| \`${cell(h.name)}\` | ${runs} | ${formatMs(h.totalDuration)} | ${cell(h.insights.map((i) => i.label).join('; ')) || '-'} |`);
      }
      out.push('');
    }

    if (data.issues.length) {
      out.push('## Issues', '', '| Severity | Code | Hook | Message |', '| --- | --- | --- | --- |');
      for (const i of data.issues) {
        out.push(`| ${ICON[i.severity]} ${i.severity} | \`${i.code}\` | \`${cell(i.hookName)}\` | ${cell(i.message)} |`);
      }
      out.push('', '## Recommendations', '');
      for (const i of data.issues) {
        out.push(`- **\`${i.code}\` ${cell(i.hookName)}**: ${i.recommendation}`);
        if (options.verbose && i.evidence.length) {
          for (const e of i.evidence.slice(0, 10)) out.push(`  - ${cell(describeEvidence(e))}`);
          if (i.evidence.length > 10) out.push(`  - …and ${i.evidence.length - 10} more`);
        }
      }
      out.push('');
    }

    if (data.hooks.length) {
      out.push('## Hooks', '', '| Hook | Type | Executions | Median | Max | Total | Issues | What it does |', '| --- | --- | ---: | ---: | ---: | ---: | --- | --- |');
      for (const h of data.hooks) {
        out.push(
          `| \`${cell(h.name)}\` | ${h.type} | ${h.executions} | ${formatMs(h.medianDuration)} | ${formatMs(h.maxDuration)} | ${formatMs(h.totalDuration)} | ${h.issues.join(', ') || '-'} | ${cell(h.insights.join('; ')) || '-'} |`,
        );
      }
      out.push('');
    }

    out.push(`<sub>Generated by hookyy v${data.version} in ${data.executionTime}ms</sub>`, '');
    return out.join('\n');
  }
}

export function describeEvidence(e: any): string {
  if (e == null || typeof e !== 'object') return String(e);
  const parts: string[] = [];
  if (e.scenario) parts.push(e.scenario);
  if (typeof e.duration === 'number') parts.push(formatMs(e.duration));
  if (Array.isArray(e.tags)) parts.push(`tags: ${e.tags.join(' ') || '(none)'}`);
  if (e.expected) parts.push(`expected: ${e.expected}`);
  if (e.declared) parts.push(`declared at ${e.declared}`);
  if (e.error) parts.push(`error: ${e.error}`);
  if (typeof e.runs === 'number' && typeof e.total === 'number') {
    parts.push(`${e.runs} runs, ${formatMs(e.total)} in total${e.share ? ` (${Math.round(e.share * 100)}% of test time)` : ''}`);
  }
  return parts.length ? parts.join(' · ') : JSON.stringify(e);
}
